language: node_js
node_js:
- '11'
install:
- npm install
script:
- npm run build
- npm test
deploy:
  provider: npm
  skip_cleanup: true
  email: Trevor.Sundberg@gmail.com
  api_key:
    secure: a5dlSlKK5hFeecyscIkkLR6ThLwoY6uNPus44oH+L5GtQx0jnNTWPBwl8UXm+xPrb8TwdOWCooivJJHmI5nz4bKnMu4K615QvPZBSro7n+NMu1W/MBSR5y/jJuC1Uc5hG92cVcEPCiXTbhmVwF7Q65tVs9biyXtD9+kF0Mdux0+h+kaz5F3QbvXUgCkbyOspriP+NP+M/2oTqOZMyZjnxjZdluiCht9A26OE+KQ7km2SBi9St/Lm97K1GN9xqeHgRZ0x9yVNvpIBz4Oyer5RkNIInFgcXH+4inrUZG7e/mL8MdrUprJmM0JKd1mFfXHfEMTXIYLaFbc3u17nK7MugSwIGK2OjLnf12/a8m5XEgdOQKrrizzYP3i8jIgNApjSs602SBxx6I1MsvEHBlBfmIB/JsAT6Bh6H1lr8AcWrDxobf20FjVRa5NUYwcra4ZEMeCte93OPPStzi7k9IaGo4ryh5PVXXc4UC4pZPvTSmeupoXX2atNW+konZwPsq88fhsmbCWO849+L9xAzTtfQN1LZh5zaZp+9nKWUqxYBHX1sZ6JOKaRiuPQIY3Dwqj9GUwwemiGGiTOlMwLuxq9BKP18VhBhb+f5LFK24aLBSrLm7ZQ3JRuxvaWG1LogG4wzYtdEZw5roPNez9MEz45gIYOskplhkmzvYleC7WP3p8=
  on:
    tags: true
    repo: codesweets/file
